export const PLAYER_PLAY_SONG = 'player/playSong'
export const PLAYER_ADD_SONG = 'player/addSong'
export const PLAYER_DELETE_SONG = 'player/deleteSong'
export const PLAYER_CHANGE_SONG = 'player/changeSong'
export const PLAYER_CLEAR_QUEUE = 'player/clearQueue'
export const PLAYER_UPDATE_STATUS = 'player/updateStatus'
export const INIT_STARRED_LIST = 'INIT_STRRED_LIST'
